{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zrok.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zrok.labels" . | nindent 4 }}
    app.kubernetes.io/component: "zrok"
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

{{- if .Values.persistence.storageClass }}
  {{- if or (eq "-" .Values.persistence.storageClass) (eq "" .Values.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
  {{- end }}
{{- end }}
