{{- if .Values.enrollmentJwt }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        {{- include "httpbin.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "httpbin.fullname" . }}-hook-serviceaccount
      containers:
      - name: post-install-job
        image: {{ .Values.zitiImage.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ZITI_ROUTER_IDENTITY_DIR
            value: /tmp/httpbin-identity
          - name: PFXLOG_NO_JSON
            value: "true"
        volumeMounts:
          - mountPath: {{ .Values.execMountDir }}/{{ .Values.initScriptFile }}
            name: httpbin-config
            subPath: {{ .Values.initScriptFile }}
          - mountPath: {{ .Values.configMountDir }}/{{ .Values.configFile }}
            name: httpbin-config
            subPath: {{ .Values.configFile }}
          - mountPath: {{ .Values.configMountDir }}/{{ .Values.enrollJwtFile }}
            name: httpbin-jwt
            subPath: {{ .Values.enrollJwtFile }}
            readOnly: true
        command: ["{{ .Values.initScriptFile }}"]
        # command: ["sh", "-c", "while true; do sleep 86400; done"]
      volumes:
        - name: httpbin-config
          configMap:
            name: {{ include "httpbin.fullname" . }}-config
            items:
              - key: {{ .Values.initScriptFile }}
                path: {{ .Values.initScriptFile }}
                mode: 0555
              - key: {{ .Values.configFile }}
                path: {{ .Values.configFile }}
                mode: 0444
        - name: httpbin-jwt
          secret:
            secretName: {{ include "httpbin.fullname" . }}-jwt
            defaultMode: 0444
            items:
            - key: enrollmentJwt
              path: {{ .Values.enrollJwtFile }}
{{- end -}}