apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpbin.fullname" . }}-identity
type: Opaque
data:
  ZITI_IDENTITY_JSON: {{ required "You must set .Values.zitiIdentity to the JSON content of a Ziti identity. Try adding --set-file zitiIdentity=/tmp/ziti_id.json to your Helm command" .Values.zitiIdentity | b64enc }}
