{{- if .Values.alertmanager.zitified -}}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-configmap-reloadz-ziti-identity
type: Opaque
data:
  identityFileName: {{ .Values.alertmanager.ziti.id | b64enc  }}
{{- end }}