{{- if .Values.configmapReload.zitified -}}
apiVersion: v1
kind: Secret
metadata:
  name: configmap-reloadz-ziti-identity
type: Opaque
data:
  zitiIdentity: {{ .Values.configmapReload.ziti.id.contents | b64enc }}
{{- end }}