{{- if .Values.server.scrape.id -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-scrape-identity-secret
type: Opaque
data:
  zid: {{ .Values.server.scrape.id.contents | b64enc  }}
{{- end }}
