#######
# Edge Signer CA
######

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziti-controller.fullname" . }}-edge-root-cert
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  commonName: ziti-signing-root-ca
  secretName: {{ include "ziti-controller.fullname" . }}-edge-root-secret
  isCA: true
  duration: {{ .Values.ca.duration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  usages:
    - digital signature
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: {{ include "ziti-controller.fullname" . }}-selfsigned-ca-issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ziti-controller.fullname" . }}-edge-root-issuer
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "ziti-controller.fullname" . }}-edge-root-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziti-controller.fullname" . }}-edge-intermediate-cert
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  commonName: ziti-controller-edge-intermediate-ca
  secretName: {{ include "ziti-controller.fullname" . }}-edge-intermediate-secret
  isCA: true
  duration: {{ .Values.ca.duration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  usages:
    - digital signature
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: {{ include "ziti-controller.fullname" . }}-edge-root-issuer

