apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ziti-controller.fullname" . }}
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: "ziti-controller"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ziti-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "ziti-controller"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ziti-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "ziti-controller"
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: {{ .Values.dnsPolicy }}

      initContainers:
        - name: {{ .Chart.Name }}-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command: ["ziti-controller-init.sh"]
          volumeMounts:
            - mountPath: {{ .Values.execMountDir }}/ziti-controller-init.sh
              name: ziti-controller-configmap
              subPath: ziti-controller-init.sh
            - mountPath: {{ .Values.dataMountDir }}
              name: data
            - mountPath: {{ .Values.image.configPath }}
              name: ziti-controller-configmap
              subPath: ziti-controller.yaml
            - mountPath: {{ .Values.configMountDir }}/default-identity/
              name: cert-default-identity
              readOnly: true
            # - mountPath: {{ .Values.configMountDir }}/default-intermediate/
            #   name: cert-default-intermediate
            #   readOnly: true
            - mountPath: {{ .Values.configMountDir }}/web-identity/
              name: cert-web-identity
              readOnly: true
            - mountPath: {{ .Values.configMountDir }}/edge-signer/
              name: cert-edge-signer
              readOnly: true
          env:
            - name: ZITI_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                  key: admin-user
            - name: ZITI_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                  key: admin-password
            - name: PFXLOG_NO_JSON
              value: "true"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: client
            containerPort: {{ .Values.clientApi.port }}
          - name: controller
            containerPort: {{ .Values.ctrlPlane.port }}
          - name: mgmt-api
            containerPort: {{ .Values.managementApi.port }}
          {{- if .Values.prometheus.enabled }}
          - name: prometheus
            containerPort: {{ .Values.prometheus.port }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if .Values.image.command }}
          command:
          {{- range .Values.image.command }}
            - {{ . | quote }}
          {{- end }}
          {{ end }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          env:
            - name: PFXLOG_NO_JSON
              value: "true"
          volumeMounts:
            - mountPath: {{ .Values.dataMountDir }}
              name: data
            - mountPath: {{ .Values.image.configPath }}
              name: ziti-controller-configmap
              subPath: ziti-controller.yaml
            - mountPath: {{ .Values.configMountDir }}/default-identity/
              name: cert-default-identity
              readOnly: true
            - mountPath: {{ .Values.configMountDir }}/web-identity/
              name: cert-web-identity
              readOnly: true
            - mountPath: {{ .Values.configMountDir }}/edge-signer/
              name: cert-edge-signer
              readOnly: true
            # - mountPath: {{ .Values.configMountDir }}/default-intermediate/
            #   name: cert-default-intermediate
            #   readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ziti-controller-configmap
          configMap:
            name: {{ include "ziti-controller.fullname" . }}-config
            items:
              - key: ziti-controller-init.sh
                path: ziti-controller-init.sh
                mode: 0555
              - key: ziti-controller.yaml
                path: ziti-controller.yaml
                mode: 0444
        - name: cert-default-identity
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-default-identity-secret
        # - name: cert-default-intermediate
        #   secret:
        #     secretName: {{ include "ziti-controller.fullname" . }}-default-intermediate-secret
        - name: cert-edge-signer
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-edge-signer-secret
        - name: cert-web-identity
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-web-identity-secret
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "ziti-controller.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
