apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  completions: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        {{- include "ziti-controller.labels" . | nindent 8 }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "ziti-controller.fullname" . }}-init-serviceaccount
      containers:
        - name: {{ .Chart.Name }}-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command: ["{{ .Values.initScriptFile }}"]
          volumeMounts:
            - mountPath: {{ .Values.execMountDir }}/{{ .Values.initScriptFile }}
              name: ziti-controller-configmap
              subPath: {{ .Values.initScriptFile }}
            - mountPath: {{ .Values.dataMountDir }}
              name: data
            - mountPath: {{ .Values.configMountDir }}/{{ .Values.configFile }}
              name: ziti-controller-configmap
              subPath: {{ .Values.configFile }}
            - mountPath: {{ .Values.configMountDir }}/ctrl-plane-identity/
              name: cert-ctrl-plane-identity
              readOnly: true
            - mountPath: {{ .Values.configMountDir }}/web-identity/
              name: cert-web-identity
              readOnly: true
            - mountPath: {{ .Values.configMountDir }}/edge-signer/
              name: cert-edge-signer
              readOnly: true
          env:
            - name: ZITI_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                  key: admin-user
            - name: ZITI_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                  key: admin-password
            - name: ZITI_CTRL_PLANE_CA
              value: /tmp/ctrl-plane-ca
            - name: PFXLOG_NO_JSON
              value: "true"
      volumes:
        - name: ziti-controller-configmap
          configMap:
            name: {{ include "ziti-controller.fullname" . }}-config
            items:
              - key: {{ .Values.initScriptFile }}
                path: {{ .Values.initScriptFile }}
                mode: 0555
              - key: {{ .Values.configFile }}
                path: {{ .Values.configFile }}
                mode: 0444
        - name: cert-ctrl-plane-identity
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-identity-secret
        - name: cert-edge-signer
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-edge-signer-secret
        - name: cert-web-identity
          secret:
            secretName: {{ include "ziti-controller.fullname" . }}-web-identity-secret
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "ziti-controller.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
