apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-router.fullname" . }}-enrolment-jwt
type: Opaque
data:
  enrollmentJwt: {{ required "You must set .Values.enrollmentJwt to the edge routers enrolment token. Try adding --set-file enrollmentJwt=/tmp/router.jwt to your Helm command" .Values.enrollmentJwt | b64enc }}
