{{- if not (lookup "v1" "ServiceAccount" .Release.namespace (print (include "ziti-router.fullname" . ) "-serviceaccount")) }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ziti-router.fullname" . }}-serviceaccount
  namespace: {{ .Release.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziti-router.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ziti-router.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ziti-router.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ziti-router.fullname" . }}-serviceaccount
    namespace: {{ .Release.namespace }}

{{- end }}
